### ISSUE TITLE
No reply address is registered for the application

### ISSUE THREAD

**Issue by devconnectcrm** [MicrosoftDX/AuthBot#13]
Hi,

I have managed to configure my bot on azure and bot framework. When I use this on Skype it did promted me to login. Upon login am getting _"AADSTS50011: No reply address is registered for the application"_ error. 
![capture](https://cloud.githubusercontent.com/assets/19694471/22564956/64124b34-e97e-11e6-8f80-7e4ee448598b.PNG)

**Comment by g-wills** [comment]
I fixed this by going to your application:
apps.dev.microsoft.com

Click the "Edit Application Manifest" button.
Add
"http://localhost:3978/api/OAuthCallback"
to the replyUrls element.

**Comment by radzhome** [comment]
+1

**Comment by matvelloso** [comment]
Hello all,

Please note the readme page pointing to a new auth solution. This library is now deprecated so you probably want to consider moving on if you can.
