### ISSUE TITLE
Auth Bot not storing/retaining the token

### ISSUE THREAD

**Issue by kanishk-mehta** [MicrosoftDX/AuthBot#18]
Hi,

I've copied the code word for word and have followed the procedure mentioned in the video:
[Office-Dev-Show-Episode-34-Getting-Started-with-Bots-and-the-Microsoft-Graph](https://channel9.msdn.com/Shows/Office-Dev-Show/Office-Dev-Show-Episode-34-Getting-Started-with-Bots-and-the-Microsoft-Graph
)

And it works, the bot asks me for the magic number which i copy paste and give to the bot, after which it says "Thanks Kanishk Mehta. You are now logged in." which is great. But after that whatever I type, I get the message "Your credentials expired and could not be renewed automatically!" and then "In order to finish the sign out, please click at this link." and then it asks me to authenticate again... 

Please help. Below is a snapshot of my conversation with the bot. if any further details are required on my part, please let me know. @matvelloso @msftgits 

![image](https://cloud.githubusercontent.com/assets/8237602/25649006/62b495d2-2fef-11e7-8612-150ccb69fed3.png)

**Comment by matvelloso** [comment]
Sorry, catching up with this. Have you found the problem? It sounds like your bot may be throwing an exception and therefore clearing up all its state.
