### ISSUE TITLE
Not compatible with Bot Builder 3.5.9

### ISSUE THREAD

**Issue by LTsLlama** [MicrosoftDX/AuthBot#20]
After updating to Microsoft.Bot.Builder 3.5.9 I get the below error:
{
  "message": "An error has occurred.",
  "exceptionMessage": "Field not found: 'Microsoft.Bot.Builder.Dialogs.Conversation.Container'.",
  "exceptionType": "System.MissingFieldException",
  "stackTrace": "   at AuthBot.Controllers.OAuthCallbackController.<OAuthCallback>d__3.MoveNext()\r\n   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)\r\n   at AuthBot.Controllers.OAuthCallbackController.OAuthCallback(String code, String state, CancellationToken cancellationToken)\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass12.<GetExecutor>b__8(Object instance, Object[] methodParameters)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()"
}

**Comment by LTsLlama** [comment]
Resolved on fork: https://github.com/LiveTiles/AuthBot

**Comment by jamesmcroft** [comment]
Have you submitted a pull request for this change?

**Comment by YTsalko** [comment]
@DL-LiveTiles could you please tell what is the root cause of this problem?

And interesting if contributors will also fix it here?

**Comment by LTsLlama** [comment]
@jamesmcroft No, new to Git so just forked and worked on that. Happy to redo if needed.
@YTsalko All I did was update to the latest NuGet version of the bot framework.

**Comment by selinagabes** [comment]
Having the same problem, have the updates been made yet?

**Comment by kenakamu** [comment]
I guess just updating package.config for BotBuilder to new version will do.

**Comment by selinagabes** [comment]
@kenakamu I believe that the packages.config for the AuthBot assembly need to be updated to match the BotBuilder update

**Comment by jamesmcroft** [comment]
I'll update and create a PR

**Comment by matvelloso** [comment]
Fixed
