### ISSUE TITLE
Can the magic number be removed for single user chats

### ISSUE THREAD

**Issue by LTsLlama** [MicrosoftDX/AuthBot#23]
Hello,
Our bot only supports single user chats and therefore we would like to remove the pasting back of the magic number process. Found this comment in code:
`//IMPORTANT: DO NOT REMOVE THE MAGIC NUMBER CHECK THAT WE DO HERE. THIS IS AN ABSOLUTE SECURITY REQUIREMENT
//REMOVING THIS WILL REMOVE YOUR BOT AND YOUR USERS TO SECURITY VULNERABILITIES. 
//MAKE SURE YOU UNDERSTAND THE ATTACK VECTORS AND WHY THIS IS IN PLACE.`

Is there a secure way to remove the magic number process for single user use?

Thank you,
Douw

**Comment by LTsLlama** [comment]
@matvelloso I see you added this comment, can you please have a look at my question above. Thank you

**Comment by matvelloso** [comment]
While not having group chats definitely lowers the vector of attack, I recommend you to keep the magic number. The reason is that this isn't the only way how problems related to security could happen: Imagine a case where the user accidentally leaks the hyperlink used to authenticate and another user gets hold of it. That alone is enough for the second user to inject their identity into the first user, even if not using group chats. My recommendation from the security point of view is to always require the magic number to help avoiding such risks.

**Comment by LTsLlama** [comment]
Thank you for the reply @matvelloso.
Wouldn't all websites using oauth then have the same security gap?
The hypelink used to authenticate is the public MS login page and redirect urls are restricted in the AD app.
Sorry if I'm missing something.

**Comment by matvelloso** [comment]
Great question and the answer here is no, not the same risk happens in other OAuth based websites. If you look at the source of AuthBot, it injects an additional information into the sign in URL so we know for which user in that channel it came from. Websites and apps don't need that much info in the auth hyperlink. So for apps and websites, if the authentication URL leaks, there's no sensitive information in there at all, zero risk. Here, that's not the case and just the URL already exposes some level of information that would put the user at risk.

**Comment by LTsLlama** [comment]
@matvelloso, I am looking at the code and see the ResumptionCookie incl. message data is passed thru as the state on the URL. The cookie is encoded, but nonetheless I see the risk.

We can however use the token to get the username from Graph which will remove the requirement to pass that over the auth link and therefore we only have to pass the Channel Id.
Would that be a viable solution to remove the magic number?

Thank you for your help.

**!!!UPDATE!!!**
Dug deeper and the above won't work because each channel has it's own user Id and all the information is required to continue the login flow conversation.

The alternative would be to do the authentication in the WebChat and pass the token to the bot.

@matvelloso Can the magic number be removed for chat clients that have their own layer of authentication, because then a user cannot be impersonated?

**Comment by matvelloso** [comment]
Web chat and app embedded channels can use the backchannel approach for doing integrated authentication (https://docs.microsoft.com/en-us/bot-framework/bot-design-pattern-embed-web-site).

In that case you wouldn't use AuthBot at all: The web site is in charge of authentication, not the bot.

But you have to be super careful on what kind of token you have the web site passing to the bot and how the bot validates that token, or else you may have someone learning how to fake a user to the bot.

**Comment by LTsLlama** [comment]
Thank you @matvelloso
