### ISSUE TITLE
Magic number

### ISSUE THREAD

**Issue by JWiersema** [MicrosoftDX/AuthBot#32]
So the code says this about the magic number:
```
//IMPORTANT: DO NOT REMOVE THE MAGIC NUMBER CHECK THAT WE DO HERE. THIS IS AN ABSOLUTE SECURITY REQUIREMENT
                    //REMOVING THIS WILL REMOVE YOUR BOT AND YOUR USERS TO SECURITY VULNERABILITIES. 
                    //MAKE SURE YOU UNDERSTAND THE ATTACK VECTORS AND WHY THIS IS IN PLACE.
```

So why is this so? Is there any other way to get rid of the security vulnerabilities? Of course it still needs to be secure.
What I'm trying to do is authenticate a user to MS graph and then have them perform queries.
If the user didnt need to paste something from the webpage, then they could get right back to the conversation with the S4B bot using a SIP link <a href='sip:bot@domain.com'>Return to bot</a> (i think). Sadly you cannot add an initial message to the SIP link.

**Comment by LTsLlama** [comment]
Have a look at these discussions @JWiersema
https://github.com/MicrosoftDX/AuthBot/issues/23#issuecomment-308699649
https://github.com/MicrosoftDX/AuthBot/issues/26#issuecomment-310142801

**Comment by JWiersema** [comment]
Thanks mate, that clarifies things!
