### ISSUE TITLE
Skype for business

### ISSUE THREAD

**Issue by dwanless79** [MicrosoftDX/AuthBot#41]
I have created a test bot and authenitcaton works fine in the bot emulator but if i attempt to use it in skype for business i recieve the following message "Please click to sign in:" with no hyperlink or "Authentication Required" button like i do when using the bot emulator.

**Comment by EricDahlvang** [comment]
@dwanless79  I think the issue here is that buttons are not supported in Skype for Business: https://msdn.microsoft.com/en-us/skype/skype-for-business-bot-framework/docs/overview 

> Skype for Business does not support rendering the cards and buttons . The Cards and buttons sent by a bot will fallback to text in the Skype for Business clients.
