### ISSUE TITLE
Maintain multiple tokens?

### ISSUE THREAD

**Issue by miaosenwang** [MicrosoftDX/AuthBot#9]
Hello,
This project has been very helpful to me. I was able to use it to get the token to call MS Graph. 
I have a new requirement that, in additional to calling MSGraph, I also need to call Visual Studio Online. 

What would be the best way to achieve that? Since all the settings are static variables, so I guess it would require a lot of changes to this package to support that.

**Comment by Masssluis** [comment]
Hello Miaosenwang, can you explain me how did you use the access token obtained from AuthBot to make a call to MS graph API?

Thanks in Advance.

**Comment by miaosenwang** [comment]
Hello @Masssluis I used MS Graph's REST api with Authentication header: Authentication: Bearer {your token}

You can see the documentation here: https://graph.microsoft.io/en-us/docs/overview/call_api

**Comment by matvelloso** [comment]
You basically assign multiple resources to your application so the same authentication will let you get access to different resources.
